[package]
name = "laminax"
version = "0.1.0"
edition = "2024"

[dependencies]
lamina = { path = "../../lamina", features = ["encoder"] }
laminax-types = { path = "laminax-types" }
laminax-lcir = { path = "laminax-lcir" }
laminax-runtime = { path = "laminax-runtime" }
numina = { path = "../numina" }
