[package]
name = "laminax-codegen"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
lamina = ["dep:lamina"]

[dependencies]
lamina = { path = "../../lamina", features = ["encoder"], optional = true }
laminax = { package = "laminax-types", path = "../laminax-types" }
laminax-lcir = { path = "../laminax-lcir" }
